fix responsiveness on mobile view
lukesanantonio/firstbyte pull request #100
Opened 2021-04-04 17:56 UTC by atulyamiglani

1. aligned navbar items for mobile view. 
2. fixed the text alignment issue for the landing page 
3. fixed the cards for mobile view on lessonplan_find_share.html
4. fixed other issues for mobile view( email and subscribe button etc.)

2021-04-06 23:11 UTC, lukesanantonio requested changes

2021-04-06 23:11 UTC, lukesanantonio commented on curriculum/templates/curriculum/lessonplan_find_share.html
> +                    <div class="pr-4 ">
remove space

2021-04-06 23:11 UTC, lukesanantonio commented on curriculum/templates/curriculum/lessonplan_find_share.html
> +                            <div class="d-flex flex-row  justify-content-between">
remove space

2021-04-06 23:11 UTC, lukesanantonio commented on curriculum/templates/curriculum/lessonplan_find_share.html
> +                <h6 class="font-weight-bold ">Interested in sharing your curricula?</h6>
remove space

2021-04-06 23:11 UTC, lukesanantonio commented on curriculum/templates/curriculum/lessonplan_find_share.html
> +                <a class="btn btn-primary " href="{% url 'create-lesson-plan' %}">Upload my curriculum</a>
remove space

2021-04-06 23:11 UTC, lukesanantonio commented on curriculum/templates/curriculum/lessonplan_find_share.html
> +            <div class="input-group  col-sm-5 align-self-center">
remove extra space

2021-04-06 23:11 UTC, lukesanantonio commented on landing/templates/landing/landing.html
> +                <div class="input-group  col-sm-5 align-self-center">
remove extra space

2021-04-06 23:13 UTC, lukesanantonio commented
Fixes #99

2021-04-06 23:14 UTC, lukesanantonio commented
Also change breakpoints of newsletter signup to stack a little sooner. Change small to medium or medium to large or what have you.

2021-04-07 16:33 UTC, atulyamiglani commented
Fixes #100

2021-04-07 18:55 UTC, lukesanantonio approved these changes
Looks great thank you so much @atulyamiglani. Merge when ready :)

2021-04-13 19:29 UTC, merged